# Generated by Django 4.1.1 on 2026-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="modeldata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.TextField(max_length=100)),
                ("status", models.CharField(default="waiting", max_length=100)),
            ],
        ),
    ]
